### ISSUE TITLE
Searchbox replacement broken after qpr2?

### ISSUE THREAD

**Issue by abdulkarimx1** [KieronQuinn/PixelLauncherMods#151] opened 2024-04-10 23:33 UTC
Looks like searchbox replacement is broken after qpr2 changes, not sure if that's the case, but i tried to flash the module more than 10 times and it doesn't work at all.. keeps telling me to save the module
( A14 ).

**Comment by KieronQuinn** [comment] 2024-04-10 23:47
Have you tried saving the module again from the overflow menu? There was a fix for exactly this included in 2.6 but it requires re-saving the module.

**Comment by abdulkarimx1** [comment] 2024-04-11 00:42
> Have you tried saving the module again from the overflow menu? There was a fix for exactly this included in 2.6 but it requires re-saving the module.

Unfortunately it didn't work, i tried a lot, maybe someone with qpr2 can test and confirm?

**Comment by KieronQuinn** [comment] 2024-04-11 00:46
Like I said, the fix in 2.6 _was_ for QPR2, and I've been running it since without issue. All the people who reported the issue on the QPR2 betas at the time confirmed it was fixed by that update too

**Comment by abdulkarimx1** [comment] 2024-04-11 01:22
> Like I said, the fix in 2.6 _was_ for QPR2, and I've been running it since without issue. All the people who reported the issue on the QPR2 betas at the time confirmed it was fixed by that update too

It didn't work for me unfortunately, any tips or methods to try ?

**Comment by KieronQuinn** [comment] 2024-04-11 01:25
Not really, no. It could be that your ROM has some sort of modification that's breaking it, so it may get patched in a future update. There's nothing else I can do unfortunately.

**Closed by KieronQuinn** 2024-04-11 01:25 UTC
