### ISSUE TITLE
Custom icons don't work on anything other than the 4x5 grid.

### ISSUE THREAD

**Issue by catplays26** [KieronQuinn/PixelLauncherMods#33] opened 2022-04-25 16:33 UTC
Custom icons don't work on 12L with anything other than a 4x5 grid. When it is set to anything else, the icons are gray after application in the app, and nothing changes in the launcher

**Comment by catplays26** [comment] 2022-04-25 16:39
Looks like an app reset fixed it, closing this

**Comment by catplays26** [comment] 2022-04-25 16:44
I see the issue that's been closed on this, but I'm going to make a new one in case of needed logs/app changes.

**Comment by cehnemdark** [comment] 2022-05-09 21:08
It looks like I don't need to open an additional thread for this. It might be helpful to understand why some users are not able to bulk apply the icon pack "on start up" on their system. After doing this it works when I apply the icon packs. Why don't you check them out? Are they not likely?

check video
https://user-images.githubusercontent.com/49096330/167498717-1dd88281-3d84-41b4-b160-562a3ce41ae1.mp4

**Comment by KieronQuinn** [comment] 2022-05-09 21:20
Your video just shows applying a 4x5 grid and then it working, this is exactly the issue that the OP has and the issue is known.

**Comment by KieronQuinn** [comment] 2022-05-10 17:15
Fixed in 2.2. Please reboot and wait a minute or so after unlocking, after making grid size changes to allow the icon cache to be rebuilt, otherwise you may end up with only some apps appearing in PLM.

**Closed by KieronQuinn** 2022-05-10 17:15 UTC
