### ISSUE TITLE
Navigation dots of At a Glance still appear after disabling it 

### ISSUE THREAD

**Issue by shivanshkverma** [KieronQuinn/PixelLauncherMods#44] opened 2022-05-16 07:16 UTC
![FSz-fY3aMAAYixZ](https://user-images.githubusercontent.com/15206857/168538966-a88c1c07-8e80-4386-9bf2-e4dacb14f8e6.jpg)
In the above image, I'm using a KWGT at a glance widget by disabling the original at a glance but dots of the original at a glance are still visible (which appear if at a glance has more than one view, like a reminder).

**Comment by EleoXDA** [comment] 2022-05-22 22:44
Could you please add more information to your bugreport? We cannot reproduce it in several different devices and ROMs.
Please provide:
- your device
- your Android version and Security Patch date
- firmware version (if custom ROM, then its name and version)
- Launcher used (e.g. Pixel Launcher, Pixel Launcher MOD, Lawnchair 12, Lawnchair 12.1 and etc.)
- Version of KWGT at a glance and its source (e.g. Author, telegram group and etc.)

**Comment by shivanshkverma** [comment] 2022-05-23 06:57
Sure:

Aliothin (Mi11X)
Android version 12.1L and May security patch.
HentaiOS and exact version I don't know but it's from MIUI 13.
Launcher used: Pixel Launcher (no mod or anything)
Version of KWGT at a glance: https://t.me/modulesrepo/3400. Now it's updated to version 2327, the one I used was 2035.

**Comment by EleoXDA** [comment] 2022-05-23 08:35
Hello. The author of the widget asks to update the widget to the latest version to get it fixed.

**Comment by KieronQuinn** [comment] 2022-07-20 19:14
This isn't an issue with the widget. I saw it myself with a totally different widget on Monday and like I said: I know the cause.

**Comment by KieronQuinn** [comment] 2022-07-21 00:14
Fixed in 2.3

**Closed by KieronQuinn** 2022-07-21 00:14 UTC
Labels: bug
